- discovery/discovery.go
- discovery/discovery_test.go
- discovery/docker_discovery.go
- discovery/docker_discovery_test.go
- discovery/static_discovery.go
- discovery/static_discovery_test.go
- haproxy/haproxy.go
- haproxy/haproxy_test.go
- healthy/service_bridge_test.go
- main.go
- service/service.go
- service/service_test.go
- views/haproxy.cfg
This is a really important change. 
1. This will prevent issues where hosts have short names and where the search domains don't match on the Sidecar hosts. 
2. It allows for hosts to have multiple interfaces and export the containers on the specified port. 
3. It paves the way for Sidecar to serve DNS SRV records. It will be able to provide sidecar-specific hostnames that point to proper IP addresses.
Static discovery will use any provided ports or will use the default published IP when this is not specified. HAproxy will default to using the hostname as beforewhen the ports do not have IPs specified. When a Docker container reports a port with an IP address of `0.0.0.0`, `DockerDiscovery` will instead replace it with the default published IP address.
@felixgborrego @mihaitodor @bparli …
> Carry IP addresses for each port

- README.md
This is currently pointing to Spacesuit's build job in travis.
> Fix link to travis build status.

- haproxy/haproxy.go
- haproxy/haproxy_test.go
- services_delegate.go
This fixes a weird issue where, now that we're grabbing output from the HAproxy commands, SIGSTOP, SIGTSTP, SIGTTOU, and SIGTTIN signals are getting propagated up from the shell and HAproxy commands and causing the process to stop. The solution is to swallow those signals while the command is running. The implementation here lazily begins intercepting them and will continue to do so until `ResetSignals()` is called.
It's important to note that `ResetSignals()` could remove other signal handlers that have been installed on these signals in other parts of the program! Also, access to manipulating the signal handling is synchronized with a mutex. This is held locked the entire time the external executable is running because we can't risk having them turned off while it's still running and …
> Fix haproxy restart

- catalog/services_state.go
- catalog/services_state_test.go
- http.go
- http_test.go
- when invoking `/watcher?by_service=false`, return the entire
state instead of `state.ByService()`
- add unit tests for the watcher handler
Note: the `params` parameter of `watchHandler` won't receive the HTTP query parameters, so I had to extract `by_service` from `req.URL.Query()`.
> Add watcher by_service optional query parameter

- catalog/services_state.go
- catalog/services_state_test.go
This fixes a bug in the host expiration where a host that contains only tombstone records will still cause state updates and possibly tombstone announcements to go out over gossip. The fix is simple but a couple of other defensive checks were added to make sure we don't get into an inconsistent state.
cc @mihaitodor @felixgborrego
> Don't announce empty tombstone list/notify listeners

- catalog/services_state.go
This should fix a small update race between when a service is updated and when it's announced to listeners. This may be affecting certain haproxy-api installations.
@felixgborrego
> Fix update race

- main.go
- service/service.go
- sidecarhttp/envoy_api.go
- sidecarhttp/envoy_api_test.go
- sidecarhttp/http.go
- sidecarhttp/http_api_test.go
This is a first pass, dead simple implementation of the Envoy CDS, SDS, and LDS APIs on top of Sidecar. There are some hardcoded settings here and a bit of work to be done to make things more useful. But it fairly closely approximates the current HAproxy functionality on Envoy, with a few exceptions. I have tested it with [this Docker container build](https://gist.github.com/relistan/55a6f54bfc2b79d03eb0c8327c2aeb1c)
> Add Envoy proxy API

- discovery/docker_discovery.go
- docker/s6/services/.s6-svscan/crash
- docker/s6/services/.s6-svscan/finish
Please note that the `containerCache` map is accessed without a lock guard from [`pruneContainerCache`](https://github.com/newrelic/sidecar/blob/62cd8e42c841c53758136fcd71f8f7b680e2826a/discovery/docker_discovery.go#L268) as well, but that seems safe, since this method is only called from [`getContainers `](https://github.com/newrelic/sidecar/blob/62cd8e42c841c53758136fcd71f8f7b680e2826a/discovery/docker_discovery.go#L231), which locks the RWMutex before invoking it.
I also added an s6 `finish` script to match [what we have in Lazyraster](https://github.com/Nitro/lazyraster/blob/master/docker/s6/services/.s6-svscan/finish) as discussed [here](https://github.com/newrelic/sidecar/issues/38#issuecomment-363581128).
> Fix concurrent map writes

- discovery/docker_discovery.go
- discovery/docker_discovery_test.go
- main.go
This extracts the container cache from the docker discovery system to a separate type. All access to the cache uses locks now, so we shouldn't see any more crashes related to concurrent map access for this module.
> Fix discovery

- sidecarhttp/envoy_api.go
- sidecarhttp/envoy_api_test.go
With these changes, Envoy will be able to update a service if all of its instances are taken offline. It should also handle empty LDS and CDS replies gracefully.
Here are the errors reported by Envoy which I have addressed through these changes:
```
[2018-06-29 16:20:35.125][87][debug][router] source/common/router/router.cc:248] [C0][S17692232238502726859] cluster 'sidecar-lds' match for URL '/v1/listeners/nitro-dev/ODBM0NEFD59L'
...
[2018-06-29 16:20:35.126][87][warning][upstream] source/server/lds_subscription.cc:68] lds: fetch failure: JSON at lines 1-1 does not conform to schema.
Invalid schema: #/properties/listeners
Schema violation: type
Offending document key: #/listeners
```
and
```
[2018-06-29 16:20:40.007][87][debug][router] source/common/router/router.cc:248] …
```
> Fix Envoy API to obey the Envoy schema

- README.md
- sidecarhttp/envoy_api.go
- sidecarhttp/envoy_api_ffjson.go
- sidecarhttp/envoy_api_test.go
This change allows users to set the `ProxyMode=tcp` Docker label when using Envoy. The payload of the listenersHandler API call will instruct Envoy to use [TCP proxy mode](https://www.envoyproxy.io/docs/envoy/v1.7.0/api-v1/network_filters/tcp_proxy_filter).
Thanks a lot @sbz for doing the hard work of untangling the Envoy documentation and coming up with the initial prototype!
TODO:
>  Enable TCP proxy support in Envoy API

- README.md
This fixes #29.
For now, `gonitro/envoyproxy` on Docker Hub has both tracing and non-tracing versions as separate tags, so we don't use the `latest` tag. We'll address this in the future.
> Fix Envoy example in Readme

- README.md
- config.go
- main.go
Fixes #26 by making the Memberlist BindPort configurable via the `SIDECAR_BIND_PORT` environment variable.
Note that we are setting the Memberlist AdvertisePort to the same value.
> Expose bind port

- healthy/service_bridge.go
Fixes #28. [CheckForService](https://github.com/Nitro/sidecar/blob/906372616ca1dac8143c9cc34f98a0814bcda10c/healthy/service_bridge.go#L130) will invoke `defaultCheckForService` when `check.Type` is not set via the `HealthCheck` label explicitly on the service.
> Fix logging in fetchCheckForService

- discovery/discovery.go
- discovery/docker_discovery.go
- discovery/docker_discovery_test.go
- discovery/static_discovery_test.go
- main.go
- services_delegate.go
Looks like we're missing some error checks in there and we should keep on retrying to connect even if `d.ClientProvider()` fails the first time.
Also, the `for` loop in `manageConnection` was calling `docker.NewClient(d.endpoint)` instead of `d.ClientProvider()`, which seems wrong to me, because `d.ClientProvider()` resolves to `d.getDockerClient()`, which is able to call `docker.NewClientFromEnv()`, in case `d.endpoint == ""`.
I also fixed a flaky test in `static_discovery`.
TODO:
> Check errors in docker_discovery.go

- .travis.yml
- README.md
Apparently, their new YAML linter doesn't like those quotes in the deploy `condition`. I think it should be fine without them, but not sure. Will think about it when we'll do a release.
> Migrate to travis-ci.com

- catalog/services_state.go
- catalog/services_state_test.go
- healthy/healthy.go
- receiver/http_test.go
- receiver/receiver.go
- service/service.go
- services_delegate.go
- sidecarhttp/envoy_api_test.go
- sidecarhttp/http_api.go
- sidecarhttp/http_api_test.go
- sidecarhttp/http_test.go
- ui/app/services/services.html
- ui/app/services/services.js
- ui/package.json
Hey @relistan this is a WIP of your notes from #44.
I believe this covers the required functionality except the following two items:
- [this code](https://github.com/Nitro/sidecar/blob/8912f899907a44f2c1ca969d00aeff7422b8ad61/catalog/services_state.go#L474-L476) in `IsNewService` returns true for `DRAINING` services. This happens because BroadcastServices will get the servicesList from `monitor.Services()`, which will return the service with status `ALIVE` due to the healthcheck. Then `svc.Status` will be `ALIVE` and `found.Status` will be `DRAINING`, so the `if` statement succeeds. I see the `DRAINING` state propagating in under 10 seconds in a test environment, so that should be fine.
I'll continue digging through the code to see how much would need to be changed for these.
Please let …
> Add service DRAINING status and a handler for the `drain` HTTP API endpoint

- envoy/adapter/adapter.go
- envoy/server.go
- envoy/server_test.go
When I implemented the Envoy adapter, I didn't notice this `validate_clusters` field in the `HTTP route configuration` (see [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route.proto#envoy-api-msg-routeconfiguration)). Although the docs say that "this setting default to false if the route table is loaded dynamically via the rds option", for some reason it seems to be set to `true` when the connection manager is of type `HTTPConnectionManager` and `false` when the connection manager is of type `TcpProxy`. The reason I added all that custom logic in server.go was to avoid Envoy spewing out errors and rejecting listeners for which clusters haven't been created yet because the go-control-plane sends listener and cluster updates to Envoy independently without a predefined …
> Skip Envoy HTTPConnectionManager cluster validation and simplify Envoy server code

- docker/s6/services/sidecar.svc/run
If $ENVOY_BIND_IP is not set, use $HAPROXY_BIND_IP instead.
> Add $ENVOY_BIND_IP to the loopback interface

- envoy/adapter/adapter.go
- envoy/server_test.go
The listener names need to be unique for each service port and the virtual host names need to be set to the service name, just like in the legacy JSON REST API implementation.
> Fix Envoy gRPC API listener names

- envoy/adapter/adapter.go
- envoy/server.go
- envoy/server_test.go
This allows ADS to retrieve endpoints directly if needed. The dynamic clusters returned by CDS use EDS discovery, so they have to fetch their endpoints via ADS instead of having them embedded directly as before.
Also remove deprecated APIs for the Envoy gRPC API.
These changes require Envoy v1.12.0+.
> Use EDS clusters for the Envoy gRPC API

- services_delegate.go
In production occasionally a node will have an issue and this can generate a LOT of logs. Sampling should reduce the volume but still make it pretty obvious that something is wrong.
> Sample logging for no broadcasts

- envoy/adapter/adapter.go
- envoy/adapter/adapter_test.go
There is a non-infrequent problem where people launch a service that is squatting on the ports of another service. We handled this in the HAproxy code, but not in the Envoy code. Unfortunately, when this happens, Envoy goes absolutely apeshit logging and reloading. This fills disks and hogs up CPU. This PR should prevent that from happening.
>  Check for port collisions before telling Envoy

- config/config.go
- main.go
We need to be able to configure more items in the memberlist config. This allows changing both the handoff buffer size and the gossip interval.
> Allow more memberlist configuration

- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
This filters down the services to those which:
* Have a `NodePort` defined since this is required for this method of announcement
* Have a Label called `ServiceName` so we can be sure this is a service we want to announce
> Better filter the services we want to announce

- catalog/services_state.go
- catalog/services_state_test.go
- catalog/url_listener_test.go
- service/service.go
- service/service_test.go
There is a longstanding bug that very, very rarely occurs, where somehow some old state gets stuck in the cluster and won't get cleared. It can also cause a gossip loop to happen where nodes are constantly talking about this old piece of state. I think this patch will prevent that from happening.
> Ignore records older than TOMBSTONE_LIFESPAN

- catalog/services_state.go
- catalog/services_state_test.go
In some weird edge case that rarely occurs, we can end up with some stale state that keeps getting broadcast around. This has happened maybe a dozen times in 8 years. This was a PITA because it required restarting all the nodes at once, which is potentially disruptive. This fix takes the approach that if we receive a stale update, we look to see if we also have it in our state. If we do, we drop the update on the floor *and also remove the service entry from our state*. If it were an erroneous deletion, we'll shortly get a newer update and possible re-add it. But then the decision is left up to the remote node and we don't attempt to resolve the mismatch. We had a production issue with this in progress and deploying this code fixed it.
> Prevent stale state from sitting around if we missed the event

- README.md
- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
- discovery/kubernetes_support.go
This finally goes the last step, and pulls all the pod info from the API. If Sidecar runs as a DaemonSet, this allows it to discover and announce for each node, using the API as the reference. This could end up with a lot of API calls if it were to run on many tens of nodes. For now, for our use case (the only people running it, I think), this should work fine.
> Do real, full discovery of pods by host

- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
- discovery/kubernetes_support.go
K8s-hosted services were stamping on each other because hostname + ID is used as a unique identifier. This reverts to using the K8s Pod UID as the ID. They are detectable vs Mesos IDs because they are UUIDs and contain dashes.
> Need a unique ID, use UID again

- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
This adds a test to show the problem, then fixes the problem. Also cleans up the code a little bit. The origin of the problem was the very famous Go for loop gotcha with pointers to the loop variable. No matter how long you've worked in Go, this mistake sometimes happens. It will be permanently fixed in Go 1.22. Can't wait.
> Fix bug in K8s service disco with duped fields

- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
- discovery/kubernetes_support.go
Reduce CPU and memory, don't launch large number of goroutines. Filter for `ServiceName` and anything not labeled `SidecarDiscover: false`
> Lots of fixes for K8s API support

- catalog/services_state.go
- catalog/view.go
- discovery/kubernetes_api_discovery.go
- discovery/kubernetes_api_discovery_test.go
- discovery/kubernetes_support.go
- receiver/receiver_test.go
- service/service.go
- service/service_test.go
This uses a `ProxyMode` label in K8s the same way that we use the Docker label.
Additional changes are just from a `go fmt ./...`
> Support ProxyMode label on K8s

- Makefile
- discovery/kubernetes_api_discovery.go
`ws` proxymode is required for websocket services. This PR adds that mode and tidies up the makefile so you don't have to copy round the sidecar binary
> [k8s] Add ws proxy mode
